### ISSUE TITLE
Benchmark against `boost::dynamic_bitset`?

### ISSUE THREAD

**Issue by Cons-Cat** [bkille/BitLib#42]
My understanding is that one of the current popular solutions to this library's problem-statement is [`boost::dynamic_bitset`](https://www.boost.org/doc/libs/1_81_0/libs/dynamic_bitset/dynamic_bitset.html). I think perhaps adding that to the benchmark might be useful for people considering this library.

**Comment by bkille** [comment]
Hi @Cons-Cat! Sorry for the late reply. I have some benchmarks to `pinam45`'s dynamic_bitset implementation [here](https://github.com/pinam45/dynamic_bitset/tree/master), which seems to have a similar interface to Boost's.
